CleanBlocks:
  ExecutionIntervalInHours: 24 # how often to run the job
  RecordRetentionDays: 14 # delete records older thhan
  Host:  "localhost" # db connection host
  Port:  5432  # db connection port
  Username: "postgres" # db connection username
  Password: "postgres" # db connection password
  DBName:  "postgres"  # db connection database
  Scheme:  "postgres" # db connection schema, postgres, mysql, etc...