# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
version: 2

before:
  hooks:
    - make test
#    - make run_e2e_tests
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^.vscode:'
      - '^test:'


# ---------------------------
# Builder
# ---------------------------
builds:
  - skip: true

# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: false
  name_template: "Release v{{.Version}}"
  footer: |
    ## Full Changelog: 
    You can find fll changelog here: https://github.com/bitcoin-sv/arc/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## Docker Image:
    You can find docker container at [Docker Hub](https://hub.docker.com/r/bsvb/arc)
    or get it by running `docker pull bsvb/arc:{{.Version}}`
