# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
version: 2

before:
  hooks:
    - make test
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^.vscode:'
      - '^test:'
# ---------------------------
# Publishers
# ---------------------------
# publishers:
#  - name: "Publish GoDocs"
#    cmd: make godocs
# ---------------------------
# Builder
# ---------------------------
builds:
  - skip: true
# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: false
  name_template: "Release v{{.Version}}"
