repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/dtaivpp/commit-msg-regex-hook
    rev: v0.2.2
    hooks:
      - id: commit-msg-regex-hook
        args: [ "--pattern='^(feat|chore|deps|sec|fix|refactor|docs|build|ci|test)(\\([A-Z]{3,6}-[0-9]{3,6}\\))?: .+$'",
                "--failure_message='Commits should match the pattern: <type>(CODE-XXX)?: Message, where <type> is one of feat, sec, fix, refactor, docs, build, ci, and (CODE-XXX) is optional.'" ]
        stages: [ commit-msg ]
