---
logLevel: DEBUG # mode of logging. Value can be one of DEBUG | INFO | WARN | ERROR
logFormat: text # format of logging. Value can be one of text | json | tint
profilerAddr: localhost:9999 # address to start profiler server on
statisticsServerAddress: localhost:9005 # address to start statistics server on
prometheusEndpoint: /metrics # endpoint for prometheus metrics
tracing: true # enable trancing
dataFolder: data # name of data folder
grpcMessageSize: 100000000 # maximum grpc message size
network: regtest # bitcoin network to connect to

peerRpc: # rpc configuration for bitcoin node
  password: bitcoin
  user: bitcoin
  host: localhost
  port: 18332

peers: # list of bitcoin node peers to connect to
  - host: localhost
    port:
      p2p: 18333
      zmq: 28332
  - host: localhost
    port:
      p2p: 18334
  - host: localhost
    port:
      p2p: 18335

callbacker:
  listenAddr: localhost:8021 # address space for callbacker to listen on. Can be for example localhost:8021 or :8021 for listening on all addresses
  dialAddr: localhost:8021 # address for other services to dial callbacker service
  profilerAddr: localhost:9994
  interval: 30s
  expiryInterval: 3m

metamorph:
  listenAddr: localhost:8001 # address space for metamorph to listen on. Can be for example localhost:8001 or :8001 for listening on all addresses
  dialAddr: localhost:8001 # address for other services to dial metamorph service
  log:
    file: ./data/metamorph.log # location of log file
  db:
    mode: badger # db mode inidicates which db to use. Value can be one of badger | postgres | dynamodb
    postgres: # postgres db configuration in case that mode: postgres
      host: localhost
      port: 5432
      name: metamorph
      user: arc
      password: arc
      maxIdleConns: 10 # maximum idle connections
      maxOpenConns: 80 # maximum open connections
      sslMode: disable
    dynamoDB:
      tableNameSuffix: regtest
    cleanData:
      recordRetentionDays: 14 # number of days for which data is kept in the storage before it can be deleted
  processorCacheExpiryTime: 24h # time after which processor cache is cleaned
  checkUtxos: false # force check each utxo for validity. If enabled ARC connects to bitcoin node using rpc for each utxo
  statsKeypress: false # enable stats keypress. If enabled pressing any key will print stats to stdout
  profilerAddr: localhost:9992 # address to start profiler server on
  network:
    fixedIp: true # Denotes if ARC is running with fixed IP addresses
    ipAddressHint: ^172.28.*

blocktx:
  listenAddr: localhost:8011 # address space for blocktx to listen on. Can be for example localhost:8011 or :8011 for listening on all addresses
  dialAddr: localhost:8011 # address for other services to dial blocktx service
  db:
    mode: sqlite # db mode indicates which db to use. Value can be one of sqlite | sqlite_memory | postgres
    postgres: # postgres db configuration in case that mode: postgres
      host: localhost
      port: 5432
      name: blocktx
      user: arc
      password: arc
      maxIdleConns: 10 # maximum idle connections
      maxOpenConns: 80 # maximum open connections
      sslMode: disable
    cleanData:
      recordRetentionDays: 14 # number of days for which data is kept in the storage before it can be deleted
      executionIntervalHours: 24
  profilerAddr: localhost:9993 # address to start profiler server on
  startingBlockHeight: 100 # starting block height for blocktx to start from. blocktx will not request blocks lower than this height

broadcaster:
  apiURL: https://test-api.taal.com/arc # api url for broadcaster to connect to

api:
  address: localhost:9090 # address to start api server on
  wocApiKey: "mainnet_XXXXXXXXXXXXXXXXXXXX" # api key for www.whatsonchain.com
  defaultPolicy: # default policy of bitcoin node
    excessiveblocksize: 2000000000
    blockmaxsize: 512000000
    maxtxsizepolicy: 100000000
    maxorphantxsize: 1000000000
    datacarriersize: 4294967295
    maxscriptsizepolicy: 100000000
    maxopsperscriptpolicy: 4294967295
    maxscriptnumlengthpolicy: 10000
    maxpubkeyspermultisigpolicy: 4294967295
    maxtxsigopscountspolicy: 4294967295
    maxstackmemoryusagepolicy: 100000000
    maxstackmemoryusageconsensus: 200000000
    limitancestorcount: 10000
    limitcpfpgroupmemberscount: 25
    maxmempool: 2000000000
    maxmempoolsizedisk: 0
    mempoolmaxpercentcpfp: 10
    acceptnonstdoutputs: true
    datacarrier: true
    minminingtxfee: 1e-8
    maxstdtxvalidationduration: 3
    maxnonstdtxvalidationduration: 1000
    maxtxchainvalidationbudget: 50
    validationclockcpu: true
    minconsolidationfactor: 20
    maxconsolidationinputscriptsize: 150
    minconfconsolidationinput: 6
    minconsolidationinputmaturity: 6
    acceptnonstdconsolidationinput: false

k8sWatcher:
  namespace: arc-testnet
