version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=arcuser
      - POSTGRES_PASSWORD=arcpass
      - POSTGRES_DB=arcdb_test
    ports:
      - '5432:5432'
