version: '3'
services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.0.15
    ports:
      - "18332:18332"
    expose:
      - "18332"
      - "18333"
      - "28332"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./test/config/bitcoin.conf:/data/bitcoin.conf
    command: [   "/entrypoint.sh", "bitcoind",
               "-maxstackmemoryusageconsensus=1000000000", "-excessiveblocksize=100000000", "-minminingtxfee=0.00000500"]
  arc:
    build: .
    ports:
      - "8011:8011"
      - "9090:9090"
      - "9999:9999"
    volumes:
      - ./config.yaml:/service/config.yaml
    depends_on:
      - node1

  tests:
    build: .
    environment:
      NODE_IP: "node1"
      ARC_URL: "http://localhost:9090"
    depends_on:
      - arc
    healthcheck:
      test: ["CMD","curl", "http://arc:9090/v1/tx"]
    command: ["go","test", "-v", "./test/..."]
