version: '3'
services:
  arc:
    build: .
    ports:
      - "8011:8011"
      - "9999:9999" # additional port for debugging
    environment:
      - ARC_DATABASE_CONNECTION_STRING=/data/blocktx.db?cache=shared&_pragma=busy_timeout=10000&_pragma=journal_mode=WAL
      - ARC_GRPC_PORT=8011
      - ARC_PROMETHEUS_ENDPOINT=/metrics
      - ARC_DEBUG_PPROF=http://arc:9999/debug/pprof # use service name instead of localhost
    volumes:
      - ./arc-data:/data
    networks:
      - arcnetwork
    # depends_on: include this if there are any services on which 'arc' depends
  tests:
      build: ./tests
    depends_on:
      - arc

networks:
  arcnetwork:
    driver: bridge
volumes:
  node1-data:
    external: false
  node2-data:
    external: false
  node3-data:
    external: false
