version: '3'
services:
  arc:
    build: .
    ports:
      - "8011:8011"
      - "9090:9090"
      - "9999:9999"
    environment:
      - ARC_DATABASE_CONNECTION_STRING=/data/blocktx.db?cache=shared&_pragma=busy_timeout=10000&_pragma=journal_mode=WAL
      - ARC_GRPC_PORT=8011
      - ARC_PROMETHEUS_ENDPOINT=/metrics
      - ARC_DEBUG_PPROF=http://arc:9999/debug/pprof
    volumes:
      - ./arc-data:/data

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
#    volumes:
#      - ./postgresdata:/var/lib/postgresql/data