---
logLevel: INFO
logFormat: text
network: mainnet
tracing:
  dialAddr: http://tracing:1234
  sample: 10 # sampling in percentage
broadcasting: # settings for connection to nodes
  mode: unicast # one of unicast | multicast
  multicast:
    ipv6Enabled: true # indicates whether ipv6 is enabled for multicasting
    multicastGroups: # must be specified if mode = multicast
    - "172.28.56.77" # address of multicast group, needs to be ipv6 address if ipv6 is enabled
    interfaces:
    - "eth0"
    - "eth1"
  unicast:
    peers: # list of bitcoin node peers to connect to
    - host: localhost
      port:
        p2p: 18333 # port for p2p connection
        zmq: 28332 # port for zmq connection
    - host: localhost
      port:
        p2p: 18334
    - host: localhost
      port:
        p2p: 18335
