---
logLevel: DEBUG # mode of logging. Value can be one of DEBUG | INFO | WARN | ERROR
logFormat: text # format of logging. Value can be one of text | json | tint
profilerAddr: localhost:9999 # address to start profiler server on
prometheusEndpoint: /metrics # endpoint for prometheus metrics
prometheusAddr: :2112 # port for serving prometheus metrics
grpcMessageSize: 100000000 # maximum grpc message size
network: regtest # bitcoin network to connect to
queueURL: nats://nats:4222 # URL for message queue
tracing:
  dialAddr: http://localhost:4317 # address where traces are exported to

peerRpc: # rpc configuration for bitcoin node
  password: bitcoin
  user: bitcoin
  host: localhost
  port: 18332

peers: # list of bitcoin node peers to connect to
  - host: localhost
    port:
      p2p: 18333 # port for p2p connection
      zmq: 28332 # port for zmq connection
  - host: localhost
    port:
      p2p: 18334
  - host: localhost
    port:
      p2p: 18335

metamorph:
  listenAddr: localhost:8001 # address space for metamorph to listen on. Can be for example localhost:8001 or :8001 for listening on all addresses
  dialAddr: localhost:8001 # address for other services to dial metamorph service
  db:
    mode: postgres # db mode inidicates which db to use. At the moment only postgres is offered
    postgres: # postgres db configuration in case that mode: postgres
      host: localhost
      port: 5432
      name: metamorph
      user: arc
      password: arc
      maxIdleConns: 10 # maximum idle connections
      maxOpenConns: 80 # maximum open connections
      sslMode: disable
  processorCacheExpiryTime: 24h # time after which processor cache is cleaned
  maxRetries: 1000 # maximum number of times a trasnaction is re-broadcasted
  processStatusUpdateInterval: 5s # interval of procesing status updates
  checkSeenOnNetworkOlderThan: 3h # transactions with SEEN_ON_NETWORK status will be re-requested from blocktx which are older than checkSeenOnNetworkOlderThan hours
  checkSeenOnNetworkPeriod: 4h # transactions with SEEN_ON_NETWORK status will be re-requested from blocktx which are inserted in the last checkSeenOnNetworkPeriod hours
  checkUtxos: false # force check each utxo for validity. If enabled ARC connects to bitcoin node using rpc for each utxo
  profilerAddr: localhost:9992 # address to start profiler server on
  health:
    serverDialAddr: localhost:8005 # address at which the grpc health server is exposed
    minimumHealthyConnections: 2 # minimum number of healthy peer connections for the processor to be considered healthy
  rejectCallbackContaining: [ "http://localhost", "https://localhost" ]
  stats:
    notSeenTimeLimit: 10m # amount of time after storing at which a non-seen tx will be counted towards not seen stat
    notMinedTimeLimit: 20m # amount of time after storing at which a seen but not mined tx will be counted towards not mined stat

blocktx:
  listenAddr: localhost:8011 # address space for blocktx to listen on. Can be for example localhost:8011 or :8011 for listening on all addresses
  dialAddr: localhost:8011 # address for other services to dial blocktx service
  healthServerDialAddr: localhost:8006 # address at which the grpc health server is exposed
  db:
    mode: postgres # db mode indicates which db to use. At the moment only postgres is offered
    postgres: # postgres db configuration in case that mode: postgres
      host: localhost
      port: 5432
      name: blocktx
      user: arc
      password: arc
      maxIdleConns: 10 # maximum idle connections
      maxOpenConns: 80 # maximum open connections
      sslMode: disable
  recordRetentionDays: 14 # number of days for which data integrity is ensured
  profilerAddr: localhost:9993 # address to start profiler server on
  registerTxsInterval: 10s # time interval to read from the channel registered transactions
  fillGapsInterval: 15m # time interval to check and fill gaps in processed blocks
  maxAllowedBlockHeightMismatch: 3 # maximum number of blocks that can be ahead of current highest block in blocktx, used for merkle roots verification
  mq:
    txsMinedMaxBatchSize: 20 # size of batches for transactions which got mined to be published to the message queue

api:
  address: localhost:9090 # address to start api server on
  wocApiKey: "mainnet_XXXXXXXXXXXXXXXXXXXX" # api key for www.whatsonchain.com
  defaultPolicy: # default policy of bitcoin node
    excessiveblocksize: 2000000000
    blockmaxsize: 512000000
    maxtxsizepolicy: 100000000
    maxorphantxsize: 1000000000
    datacarriersize: 4294967295
    maxscriptsizepolicy: 100000000
    maxopsperscriptpolicy: 4294967295
    maxscriptnumlengthpolicy: 10000
    maxpubkeyspermultisigpolicy: 4294967295
    maxtxsigopscountspolicy: 4294967295
    maxstackmemoryusagepolicy: 100000000
    maxstackmemoryusageconsensus: 200000000
    limitancestorcount: 10000
    limitcpfpgroupmemberscount: 25
    maxmempool: 2000000000
    maxmempoolsizedisk: 0
    mempoolmaxpercentcpfp: 10
    acceptnonstdoutputs: true
    datacarrier: true
    minminingtxfee: 1e-8
    maxstdtxvalidationduration: 3
    maxnonstdtxvalidationduration: 1000
    maxtxchainvalidationbudget: 50
    validationclockcpu: true
    minconsolidationfactor: 20
    maxconsolidationinputscriptsize: 150
    minconfconsolidationinput: 6
    minconsolidationinputmaturity: 6
    acceptnonstdconsolidationinput: false

k8sWatcher:
  namespace: arc-testnet
