name: Docker Compose Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out arc repo
      uses: actions/checkout@v2
      with:
        repository: bitcoin-sv/arc
        path: arc

    - name: Check out regtest repo
      uses: actions/checkout@v2
      with:
        repository: icellan/regtest
        path: regtest

    - name: Run Docker Compose in regtest
      run: docker-compose up -d
      working-directory: ./regtest

    - name: Run Docker Compose in arc
      run: docker-compose up -d arc
      working-directory: ./arc

    - name: Run Tests and Show Logs
      run: docker-compose run --rm tests
      working-directory: ./arc
