# .github/workflows/release.yml
name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get current branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          branch=$(echo "$branch" | xargs)
          echo "BRANCH=$branch" >> $GITHUB_ENV
#          echo "::set-output name=branch::$branch"
      - name: Echo Branch
        run: echo ${{ env.BRANCH }}
      - name: Echo Branch for Debugging
        run: echo ${{ steps.get_branch.outputs.branch }}

  goreleaser:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.branch == 'fix/check-branch-in-release-action' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
